from __future__ import annotations

from pathlib import Path

import click


@click.command("init")
@click.argument("name")
@click.option("--output-dir", "-o", default=".", help="Parent directory for the workflow")
def init_cmd(name: str, output_dir: str) -> None:
    """Scaffold a new workflow directory with a template workflow.py."""
    slug = name.lower().replace(" ", "-").replace("_", "-")
    target = Path(output_dir) / slug

    if target.exists():
        click.echo(f"Error: Directory '{target}' already exists.", err=True)
        raise SystemExit(1)

    target.mkdir(parents=True)
    (target / "custom_tools").mkdir()
    (target / "dispatchers").mkdir()

    workflow_template = f'''from architect.primitives import (
    EntityDefinition,
    FieldDef,
    ToolDefinition,
    WorkflowDefinition,
)


item = EntityDefinition(
    name="item",
    fields=[
        FieldDef("name", str, required=True, max_length=255),
        FieldDef("description", str, required=False, nullable=True),
    ],
    description="A basic item entity",
)


workflow = WorkflowDefinition(
    name="{name}",
    slug="{slug}",
    entities=[item],
    tools=[ToolDefinition.crud("item")],
    description="Generated by architect init",
)
'''
    (target / "workflow.py").write_text(workflow_template)
    (target / "custom_tools" / "__init__.py").write_text("")
    (target / "dispatchers" / "__init__.py").write_text("")

    click.echo(f"Workflow scaffolded at {target}/")
    click.echo("  workflow.py    — edit your entities and tools here")
    click.echo("  custom_tools/  — add custom MCP tools here")
    click.echo("  dispatchers/   — add dispatcher handlers here")
    click.echo(f"\nNext: architect plan {target}/workflow.py")
