import pytest
from enum import StrEnum
from uuid import UUID

from factory.primitives import EntityDefinition, FieldDef
from factory.generators.model_gen import generate_model


class LeadStatus(StrEnum):
    NEW = "new"
    CONTACTED = "contacted"
    CONVERTED = "converted"


@pytest.fixture
def lead_entity() -> EntityDefinition:
    entity = EntityDefinition(
        name="lead",
        fields=[
            FieldDef("name", str, required=True, max_length=255),
            FieldDef("email", str, email=True, nullable=True, required=False),
            FieldDef("lead_score", int, default=0),
            FieldDef("status", LeadStatus, default=LeadStatus.NEW),
            FieldDef("brand_id", UUID, fk="brand.id"),
            FieldDef("metadata", dict, required=False, nullable=True),
        ],
        indexes=[["email"]],
        unique_constraints=[["name"]],
    )
    entity.slug = "asos"
    return entity


@pytest.fixture
def minimal_entity() -> EntityDefinition:
    return EntityDefinition(
        name="tag",
        fields=[
            FieldDef("label", str, required=True, max_length=100),
        ],
    )


class TestModelGenerator:
    def test_generates_valid_python(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        assert output.exists()
        content = output.read_text()
        compile(content, str(output), "exec")

    def test_contains_auto_generated_header(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "AUTO-GENERATED by The Factory" in content

    def test_contains_class(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "class Lead(Base):" in content

    def test_contains_tablename(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert '__tablename__ = "asos_leads"' in content

    def test_contains_id_field(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "id: Mapped[uuid.UUID]" in content

    def test_contains_timestamps(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "created_at" in content
        assert "updated_at" in content

    def test_contains_fk(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "ForeignKey" in content
        assert "asos_brands.id" in content

    def test_contains_enum(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "class LeadStatus(StrEnum):" in content

    def test_contains_index(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "Index(" in content

    def test_contains_unique_constraint(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "UniqueConstraint(" in content

    def test_contains_jsonb(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "JSONB" in content

    def test_contains_base_import(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        content = output.read_text()
        assert "from factory.core.database import Base" in content

    def test_minimal_entity_no_fk_no_enum(self, minimal_entity, tmp_path):
        output = generate_model(minimal_entity, tmp_path)
        content = output.read_text()
        compile(content, str(output), "exec")
        assert "class Tag(Base):" in content
        assert '__tablename__ = "tags"' in content
        assert "ForeignKey" not in content
        assert "StrEnum" not in content

    def test_output_filename(self, lead_entity, tmp_path):
        output = generate_model(lead_entity, tmp_path)
        assert output.name == "models.py"

    def test_fk_pluralization_y_ending(self, tmp_path):
        """FK to a 'category' entity should produce 'categories' not 'categorys'."""
        entity = EntityDefinition(
            name="product",
            fields=[
                FieldDef("title", str, required=True, max_length=255),
                FieldDef("category_id", UUID, fk="category.id"),
            ],
        )
        entity.slug = "shop"
        output = generate_model(entity, tmp_path)
        content = output.read_text()
        assert "shop_categories.id" in content
        assert "shop_categorys" not in content

    def test_fk_pluralization_s_ending(self, tmp_path):
        """FK to a 'status' entity should produce 'statuses' not 'statuss'."""
        entity = EntityDefinition(
            name="task",
            fields=[
                FieldDef("name", str, required=True, max_length=255),
                FieldDef("status_id", UUID, fk="status.id"),
            ],
        )
        entity.slug = "pm"
        output = generate_model(entity, tmp_path)
        content = output.read_text()
        assert "pm_statuses.id" in content
        assert "pm_statuss" not in content

    def test_fk_pluralization_no_slug(self, tmp_path):
        """FK pluralization should work without slug too."""
        entity = EntityDefinition(
            name="article",
            fields=[
                FieldDef("title", str, required=True),
                FieldDef("category_id", UUID, fk="category.id"),
            ],
        )
        output = generate_model(entity, tmp_path)
        content = output.read_text()
        assert "categories.id" in content
        assert "categorys" not in content

    def test_date_field_in_model(self, tmp_path):
        """Date fields should produce correct SA imports and mapped types."""
        from datetime import date

        entity = EntityDefinition(
            name="event",
            fields=[
                FieldDef("title", str, required=True, max_length=255),
                FieldDef("event_date", date, nullable=True, required=False),
            ],
        )
        entity.slug = "cal"
        output = generate_model(entity, tmp_path)
        content = output.read_text()
        compile(content, str(output), "exec")
        assert "from datetime import date, datetime" in content
        assert "Date," in content
        assert "event_date: Mapped[date | None]" in content
