import pytest
from enum import StrEnum
from uuid import UUID

from architect.primitives import EntityDefinition, FieldDef
from architect.generators.schema_gen import generate_schema


class LeadStatus(StrEnum):
    NEW = "new"
    CONTACTED = "contacted"
    CONVERTED = "converted"


@pytest.fixture
def lead_entity() -> EntityDefinition:
    entity = EntityDefinition(
        name="lead",
        fields=[
            FieldDef("name", str, required=True, max_length=255),
            FieldDef("email", str, email=True, nullable=True, required=False),
            FieldDef("lead_score", int, default=0),
            FieldDef("status", LeadStatus, default=LeadStatus.NEW),
            FieldDef("brand_id", UUID, fk="brand.id"),
            FieldDef("metadata", dict, required=False, nullable=True),
        ],
        indexes=[["email"]],
        unique_constraints=[["name"]],
    )
    entity.slug = "asos"
    return entity


@pytest.fixture
def minimal_entity() -> EntityDefinition:
    return EntityDefinition(
        name="tag",
        fields=[
            FieldDef("label", str, required=True, max_length=100),
        ],
    )


class TestSchemaGenerator:
    def test_generates_valid_python(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        assert output.exists()
        content = output.read_text()
        compile(content, str(output), "exec")

    def test_contains_auto_generated_header(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "AUTO-GENERATED by The Architect" in content

    def test_contains_create_schema(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "class LeadCreate(BaseModel):" in content

    def test_contains_update_schema(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "class LeadUpdate(BaseModel):" in content

    def test_contains_read_schema(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "class LeadRead(BaseModel):" in content

    def test_read_has_from_attributes(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "from_attributes=True" in content

    def test_create_has_required_field(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "name: str" in content

    def test_create_has_fk_field(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "brand_id: uuid.UUID" in content

    def test_update_excludes_fk(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        # Extract just the Update class section
        update_start = content.index("class LeadUpdate")
        update_end = content.index("class LeadRead")
        update_section = content[update_start:update_end]
        assert "brand_id" not in update_section

    def test_update_all_optional(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        update_start = content.index("class LeadUpdate")
        update_end = content.index("class LeadRead")
        update_section = content[update_start:update_end]
        # Every field line should have "None" default
        field_lines = [
            line.strip()
            for line in update_section.split("\n")
            if ":" in line and "class " not in line and line.strip()
        ]
        for line in field_lines:
            assert "None" in line, f"Field not optional: {line}"

    def test_read_has_timestamps(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        read_start = content.index("class LeadRead")
        read_section = content[read_start:]
        assert "created_at: datetime" in read_section
        assert "updated_at: datetime" in read_section

    def test_read_has_id(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        read_start = content.index("class LeadRead")
        read_section = content[read_start:]
        assert "id: uuid.UUID" in read_section

    def test_email_uses_emailstr(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "EmailStr" in content

    def test_field_with_max_length(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        content = output.read_text()
        assert "max_length=255" in content

    def test_minimal_entity(self, minimal_entity, tmp_path):
        output = generate_schema(minimal_entity, tmp_path)
        content = output.read_text()
        compile(content, str(output), "exec")
        assert "class TagCreate(BaseModel):" in content
        assert "class TagUpdate(BaseModel):" in content
        assert "class TagRead(BaseModel):" in content

    def test_output_filename(self, lead_entity, tmp_path):
        output = generate_schema(lead_entity, tmp_path)
        assert output.name == "schemas.py"

    def test_date_field_import(self, tmp_path):
        """Schema with date field should import date from datetime."""
        from datetime import date

        entity = EntityDefinition(
            name="event",
            fields=[
                FieldDef("title", str, required=True, max_length=255),
                FieldDef("event_date", date, nullable=True, required=False),
            ],
        )
        output = generate_schema(entity, tmp_path)
        content = output.read_text()
        compile(content, str(output), "exec")
        assert "from datetime import date, datetime" in content
        assert "event_date: date | None" in content
