import pytest
from enum import StrEnum
from uuid import UUID

from factory.primitives import EntityDefinition, FieldDef
from factory.generators.serialize_gen import generate_serialize


class LeadStatus(StrEnum):
    NEW = "new"
    CONTACTED = "contacted"
    CONVERTED = "converted"


@pytest.fixture
def lead_entity() -> EntityDefinition:
    entity = EntityDefinition(
        name="lead",
        fields=[
            FieldDef("name", str, required=True, max_length=255),
            FieldDef("email", str, email=True, nullable=True, required=False),
            FieldDef("lead_score", int, default=0),
            FieldDef("status", LeadStatus, default=LeadStatus.NEW),
            FieldDef("brand_id", UUID, fk="brand.id"),
            FieldDef("metadata", dict, required=False, nullable=True),
        ],
        indexes=[["email"]],
        unique_constraints=[["name"]],
    )
    entity.slug = "asos"
    return entity


@pytest.fixture
def minimal_entity() -> EntityDefinition:
    return EntityDefinition(
        name="tag",
        fields=[
            FieldDef("label", str, required=True, max_length=100),
        ],
    )


class TestSerializeGenerator:
    def test_generates_valid_python(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        assert output.exists()
        content = output.read_text()
        compile(content, str(output), "exec")

    def test_contains_auto_generated_header(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        content = output.read_text()
        assert "AUTO-GENERATED by The Factory" in content

    def test_contains_function_name(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        content = output.read_text()
        assert "def serialize_lead(" in content

    def test_uuid_fields_use_str(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        content = output.read_text()
        assert "str(instance.id)" in content
        assert "str(instance.brand_id)" in content

    def test_enum_uses_value_with_hasattr(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        content = output.read_text()
        assert 'hasattr(instance.status, "value")' in content
        assert "instance.status.value" in content

    def test_timestamps_use_isoformat(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        content = output.read_text()
        assert "instance.created_at.isoformat()" in content
        assert "instance.updated_at.isoformat()" in content

    def test_jsonb_pass_through(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        content = output.read_text()
        assert '"metadata": instance.metadata' in content

    def test_direct_access_for_simple_fields(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        content = output.read_text()
        assert '"name": instance.name' in content
        assert '"lead_score": instance.lead_score' in content

    def test_returns_dict(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        content = output.read_text()
        assert "-> dict[str, Any]" in content
        assert "return {" in content

    def test_minimal_entity(self, minimal_entity, tmp_path):
        output = generate_serialize(minimal_entity, tmp_path)
        content = output.read_text()
        compile(content, str(output), "exec")
        assert "def serialize_tag(" in content
        assert '"label": instance.label' in content

    def test_output_filename(self, lead_entity, tmp_path):
        output = generate_serialize(lead_entity, tmp_path)
        assert output.name == "serialize.py"

    def test_date_field_uses_isoformat(self, tmp_path):
        """Date fields should use .isoformat() like datetime."""
        from datetime import date

        entity = EntityDefinition(
            name="event",
            fields=[
                FieldDef("title", str, required=True, max_length=255),
                FieldDef("event_date", date, nullable=True, required=False),
            ],
        )
        output = generate_serialize(entity, tmp_path)
        content = output.read_text()
        compile(content, str(output), "exec")
        assert "instance.event_date.isoformat()" in content
