import pytest
from enum import StrEnum
from uuid import UUID

from factory.primitives import EntityDefinition, FieldDef
from factory.generators.repo_gen import generate_repository


class LeadStatus(StrEnum):
    NEW = "new"
    CONTACTED = "contacted"
    CONVERTED = "converted"


@pytest.fixture
def lead_entity() -> EntityDefinition:
    entity = EntityDefinition(
        name="lead",
        fields=[
            FieldDef("name", str, required=True, max_length=255),
            FieldDef("email", str, email=True, nullable=True, required=False),
            FieldDef("lead_score", int, default=0),
            FieldDef("status", LeadStatus, default=LeadStatus.NEW),
            FieldDef("brand_id", UUID, fk="brand.id"),
            FieldDef("metadata", dict, required=False, nullable=True),
        ],
        indexes=[["email"]],
        unique_constraints=[["name"]],
    )
    entity.slug = "asos"
    return entity


@pytest.fixture
def minimal_entity() -> EntityDefinition:
    return EntityDefinition(
        name="tag",
        fields=[
            FieldDef("label", str, required=True, max_length=100),
        ],
    )


class TestRepoGenerator:
    def test_generates_valid_python(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        assert output.exists()
        content = output.read_text()
        compile(content, str(output), "exec")

    def test_contains_auto_generated_header(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "AUTO-GENERATED by The Factory" in content

    def test_contains_class_name(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "class LeadRepository:" in content

    def test_contains_get_method(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def get(self, id: uuid.UUID)" in content

    def test_contains_list_method(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def list(" in content
        assert "limit: int = 50" in content
        assert "offset: int = 0" in content

    def test_contains_add_method(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def add(" in content
        assert "self._session.add(entity)" in content

    def test_contains_delete_method(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def delete(self, id: uuid.UUID) -> bool:" in content

    def test_uses_async_session(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "AsyncSession" in content

    def test_contains_filter_logic(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "**filters" in content
        assert "hasattr(" in content

    def test_imports_select(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "from sqlalchemy import select" in content

    def test_model_import_reference(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        content = output.read_text()
        assert "from factory.generated.asos.lead.models import Lead" in content

    def test_minimal_entity(self, minimal_entity, tmp_path):
        output = generate_repository(minimal_entity, tmp_path)
        content = output.read_text()
        compile(content, str(output), "exec")
        assert "class TagRepository:" in content

    def test_output_filename(self, lead_entity, tmp_path):
        output = generate_repository(lead_entity, tmp_path)
        assert output.name == "repository.py"
