from enum import StrEnum
from uuid import UUID

import pytest

from factory.generators.tool_gen import generate_tools
from factory.primitives import EntityDefinition, FieldDef


class LeadStatus(StrEnum):
    NEW = "new"
    CONTACTED = "contacted"
    CONVERTED = "converted"


@pytest.fixture
def lead_entity() -> EntityDefinition:
    entity = EntityDefinition(
        name="lead",
        fields=[
            FieldDef("name", str, required=True, max_length=255),
            FieldDef("email", str, email=True, nullable=True, required=False),
            FieldDef("lead_score", int, default=0),
            FieldDef("status", LeadStatus, default=LeadStatus.NEW),
            FieldDef("brand_id", UUID, fk="brand.id"),
            FieldDef("metadata", dict, required=False, nullable=True),
        ],
        indexes=[["email"]],
        unique_constraints=[["name"]],
    )
    entity.slug = "asos"
    return entity


@pytest.fixture
def minimal_entity() -> EntityDefinition:
    return EntityDefinition(
        name="tag",
        fields=[
            FieldDef("label", str, required=True, max_length=100),
        ],
    )


class TestToolGenerator:
    def test_generates_valid_python(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        assert output.exists()
        content = output.read_text()
        compile(content, str(output), "exec")

    def test_contains_register_function(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "def register(mcp: Any) -> None:" in content

    def test_contains_auto_generated_header(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "AUTO-GENERATED by The Factory" in content

    def test_contains_list_tool(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def list_leads(" in content
        assert '"""List leads with optional filters."""' in content

    def test_contains_get_tool(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def get_lead(" in content
        assert '"""Get a single lead by ID."""' in content

    def test_contains_create_tool(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def create_lead(" in content
        assert '"""Create a new lead."""' in content

    def test_contains_update_tool(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def update_lead(" in content
        assert '"""Update an existing lead."""' in content

    def test_contains_delete_tool(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "async def delete_lead(" in content
        assert '"""Delete a lead by ID."""' in content

    def test_list_has_filters(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        # email is indexed, should be a filter
        assert 'email: Annotated[str | None, "Filter by email"]' in content
        # brand_id is FK, should be a filter
        assert 'brand_id: Annotated[str | None, "Filter by brand_id"]' in content

    def test_create_has_required_fields(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        # name is required, should be positional (no default)
        assert 'name: Annotated[str, "name"]' in content

    def test_create_has_fk_fields(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        # brand_id is FK and required, should appear as required string param
        assert 'brand_id: Annotated[str, "UUID of brand"]' in content

    def test_update_excludes_fk(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        # Find the update function and check brand_id is not in its params
        update_start = content.index("async def update_lead(")
        delete_start = content.index("async def delete_lead(")
        update_section = content[update_start:delete_start]
        assert "brand_id" not in update_section

    def test_update_has_optional_fields(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        update_start = content.index("async def update_lead(")
        delete_start = content.index("async def delete_lead(")
        update_section = content[update_start:delete_start]
        assert 'name: Annotated[str | None, "Updated name"] = None' in update_section
        assert 'email: Annotated[str | None, "Updated email"] = None' in update_section
        assert 'lead_score: Annotated[int | None, "Updated lead_score"] = None' in update_section
        assert 'status: Annotated[str | None, "Updated status"] = None' in update_section
        assert 'metadata: Annotated[dict | None, "Updated metadata"] = None' in update_section

    def test_minimal_entity(self, minimal_entity, tmp_path):
        output = generate_tools(minimal_entity, tmp_path)
        assert output.exists()
        content = output.read_text()
        compile(content, str(output), "exec")
        assert "async def list_tags(" in content
        assert "async def get_tag(" in content
        assert "async def create_tag(" in content
        assert "async def update_tag(" in content
        assert "async def delete_tag(" in content
        # No FK fields means no FK filters or FK params
        assert "ForeignKey" not in content

    def test_contains_annotated_descriptions(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "Annotated[" in content
        assert '"Maximum number of results to return"' in content
        assert '"Number of results to skip"' in content
        assert '"The UUID of the lead to retrieve"' in content
        assert '"The UUID of the lead to update"' in content
        assert '"The UUID of the lead to delete"' in content

    def test_contains_serialize_wrapper(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        content = output.read_text()
        assert "def _serialize_lead(" in content
        assert "from factory.generated.asos.lead.serialize import serialize_lead" in content

    def test_output_filename(self, lead_entity, tmp_path):
        output = generate_tools(lead_entity, tmp_path)
        assert output.name == "tools.py"
